// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCztFgEd1YbjrHmlpAVMnfFeQQSi-9QHXY',
    appId: '1:444858309033:android:901fd66404b6e350644cb8',
    messagingSenderId: '444858309033',
    projectId: 'matiz-app',
    databaseURL: 'https://matiz-app-default-rtdb.firebaseio.com',
    storageBucket: 'matiz-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZF7y012GFdBjc0bip42ZMuR4R95N3fuc',
    appId: '1:444858309033:ios:28e919cbad7fee44644cb8',
    messagingSenderId: '444858309033',
    projectId: 'matiz-app',
    databaseURL: 'https://matiz-app-default-rtdb.firebaseio.com',
    storageBucket: 'matiz-app.firebasestorage.app',
    androidClientId: '444858309033-rqd8r7fjf57qttq8u18gdhn29vruekm0.apps.googleusercontent.com',
    iosClientId: '444858309033-eild50t4itpdm8v047o08bll3g2pn28h.apps.googleusercontent.com',
    iosBundleId: 'com.keepgoing.matiz',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNj33cwrDQR5D74Rjtd_h2JktZZTk4OXY',
    appId: '1:444858309033:web:993762e9fff1fb6d644cb8',
    messagingSenderId: '444858309033',
    projectId: 'matiz-app',
    authDomain: 'matiz-app.firebaseapp.com',
    databaseURL: 'https://matiz-app-default-rtdb.firebaseio.com',
    storageBucket: 'matiz-app.firebasestorage.app',
    measurementId: 'G-14JZTY316W',
  );

}